name: Java

on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build using Gradle
        run: ./gradlew assemble
      - name: Run the tests
        run: ./gradlew test
      - name: Save reports
        if: ${{ always() }}
        run: sh runner.sh
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: reports
          path: /tmp/run/reports