version: '3'
services:
  database:
    build: './database'
    ports:
      - '5432:5432'
    restart: always

  predict:
    build: 'predictor/'
    depends_on:
      - database
    entrypoint: /usr/bin/entrypoint-cli.sh

  predictor:
    build: 'predictor/'
    depends_on:
      - database
    entrypoint: /usr/bin/entrypoint-daemon.sh

  web:
    build: './web'
    depends_on:
      - database
    links:
      - database:database
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - .:/data
