name: LaTeX

on:
  push:
    paths:
      - '**.yml'
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install biber latexmk poppler-utils texlive-bibtex-extra texlive-binaries texlive-lang-european texlive-extra-utils texlive-fonts-extra texlive-science
        sudo updmap-sys --enable Map=fontawesome5.map
    - name: Compile Dutch abstract
      working-directory: ./paper/abstract-nl
      run: |
        latexmk --shell-escape -pdf extended-abstract.tex
    - name: Compile English abstract
      working-directory: ./paper/abstract-en
      run: |
        latexmk --shell-escape -pdf extended-abstract.tex
    - name: Compile paper
      working-directory: ./paper
      run: |
        latexmk --shell-escape -pdf thesis.tex
    - name: Count words
      working-directory: ./paper
      run: sh wordcount.sh
    - uses: actions/upload-artifact@master
      with:
        name: paper.pdf
        path: paper/thesis.pdf
