name: Latex

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: blang/latex

    steps:
    - uses: actions/checkout@v1
    - name: Compile paper
      working-directory: ./paper
      run: |
        latexmk --shell-escape -pdf thesis.tex
    - uses: actions/upload-artifact@master
      with:
        name: paper.pdf
        path: paper/thesis.pdf
