name: LaTeX

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: janstuemmel/latex

    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: |
        apt-get update
        apt-get install poppler-utils
    - name: Compile paper
      working-directory: ./paper
      run: |
        latexmk --shell-escape -pdf thesis.tex
    - name: Count words
      working-directory: ./paper
      run: sh wordcount.sh
    - uses: actions/upload-artifact@master
      with:
        name: paper.pdf
        path: paper/thesis.pdf
